#!/usr/bin/python3
"""Pre-build step: gzip data/*.html into a generated C header.

The web pages used to live as multi-kilobyte raw string literals inside
src/server/*Page.h, which made them awkward to edit (no syntax highlighting, no
linting, delimiter escaping) and cost ~37KB of a 1.375MB OTA slot uncompressed.

Moving them to a LittleFS partition was measured and REJECTED: nothing else in the
firmware uses a filesystem, so esp_littlefs + vfs (~58KB of code) cost more than the
~43KB of page data they would have stored — a net loss of ~14KB.

So the pages stay in the app image, but gzipped: ~33KB of HTML becomes ~13KB of
flash, and they are served with `Content-Encoding: gzip` straight from flash with no
runtime decompression and no new dependency. Every browser handles it.

Source of truth is data/*.html — plain files you can open in an editor. This script
regenerates the header on every build; the output goes to $BUILD_DIR (not src/), so
nothing generated is ever committed.
"""

import gzip
import os
import re

Import("env")

PROJECT_DIR = env.subst("$PROJECT_DIR")
DATA_DIR = os.path.join(PROJECT_DIR, "data")
OUT_DIR = os.path.join(env.subst("$BUILD_DIR"), "generated")
OUT_FILE = os.path.join(OUT_DIR, "GeneratedPages.h")


def symbol_for(filename):
    """dashboard.html -> DASHBOARD_HTML_GZ"""
    stem = os.path.splitext(filename)[0]
    return re.sub(r"[^A-Za-z0-9]", "_", stem).upper() + "_HTML_GZ"


def generate():
    if not os.path.isdir(DATA_DIR):
        raise RuntimeError("gen-pages: missing data/ directory at %s" % DATA_DIR)

    pages = sorted(f for f in os.listdir(DATA_DIR) if f.endswith(".html"))
    if not pages:
        raise RuntimeError("gen-pages: no .html files in %s" % DATA_DIR)

    os.makedirs(OUT_DIR, exist_ok=True)

    lines = [
        "#pragma once",
        "// AUTO-GENERATED by gen-pages.py from data/*.html — do not edit.",
        "// Served with Content-Encoding: gzip; see servePage() in HttpServerManager.cpp.",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
    ]

    raw_total = 0
    gz_total = 0
    for page in pages:
        with open(os.path.join(DATA_DIR, page), "rb") as handle:
            raw = handle.read()
        # mtime=0 so the output is byte-identical across builds — otherwise every
        # build would relink and every OTA image would differ for no reason.
        blob = gzip.compress(raw, compresslevel=9, mtime=0)
        raw_total += len(raw)
        gz_total += len(blob)

        sym = symbol_for(page)
        # Wrap by element count, never by character count — splitting the joined
        # string every N chars cuts hex literals in half ("0x" + newline + "fe").
        cells = ["0x%02x" % b for b in blob]
        rows = [",".join(cells[i:i + 16]) for i in range(0, len(cells), 16)]
        wrapped = "\n    " + ",\n    ".join(rows) + "\n"
        lines.append("// %s: %d -> %d bytes" % (page, len(raw), len(blob)))
        lines.append("static const uint8_t %s[] = {%s};" % (sym, wrapped))
        lines.append("static const size_t %s_LEN = sizeof(%s);" % (sym, sym))
        lines.append("")

    new_text = "\n".join(lines)

    # Only rewrite when the content actually changed, so an unchanged data/ does not
    # force a rebuild of everything that includes this header.
    if os.path.isfile(OUT_FILE):
        with open(OUT_FILE, "r", encoding="utf-8") as handle:
            if handle.read() == new_text:
                print("gen-pages: %d pages unchanged (%d -> %d bytes)"
                      % (len(pages), raw_total, gz_total))
                return

    with open(OUT_FILE, "w", encoding="utf-8") as handle:
        handle.write(new_text)
    print("gen-pages: %d pages, %d -> %d bytes gzipped (saved %d)"
          % (len(pages), raw_total, gz_total, raw_total - gz_total))


generate()
env.Append(CPPPATH=[OUT_DIR])
